apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dockerhub
  namespace: {{ .Values.namespace.name }}
data:
  .dockerconfigjson: {{ .Values.secrets.dockerhub }}
type: kubernetes.io/dockerconfigjson
