name: Helm Lint

on:
  pull_request:
    branches:
      - main

jobs:
  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Helm Lint
        id: lint-chart
        run: helm lint . --strict

      - name: Helm Template
        id: lint-template
        run: helm template .
